#!/usr/bin/env bash
# ===================================================================
#  StreamBridge :: local installation
#
#  Installs into a user-local prefix. No root, no system directories, and
#  nothing outside $HOME is touched.
#
#  Usage:
#    ./scripts/install.sh                 # from a checkout
#    ./scripts/install.sh --prefix DIR    # somewhere else
#    ./scripts/install.sh --no-service    # skip the systemd user unit
#    ./scripts/install.sh --dev           # also install the dev extras
# ===================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

PREFIX="${HOME}/.local"
BIN_DIR=""
NO_SERVICE=0
WITH_DEV=0
VENV_DIR=".venv"

usage() {
    sed -n '3,14p' "$0" | sed 's/^#  \{0,1\}//'
    exit "${1:-0}"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)     PREFIX="${2:?--prefix needs a directory}"; shift 2 ;;
        --no-service) NO_SERVICE=1; shift ;;
        --dev)        WITH_DEV=1; shift ;;
        --venv)       VENV_DIR="${2:?--venv needs a directory}"; shift 2 ;;
        -h|--help)    usage 0 ;;
        *)            printf 'Unknown option: %s\n' "$1" >&2; usage 1 ;;
    esac
done

say()  { printf '\033[1;32m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$1" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$1" >&2; exit 1; }

BIN_DIR="${PREFIX}/bin"

command -v python3 >/dev/null 2>&1 || die "python3 not found (3.11 or newer is required)"
python3 - <<'PY' || die "python3 3.11 or newer is required"
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY
say "python $(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')"

# ------------------------------------------------------------------
#  Virtual environment
#
#  Kept out of $HOME/.local by default so an uninstall can remove the
#  project without guessing. Everything the install needs stays inside
#  the checkout.
# ------------------------------------------------------------------
[ -d "$VENV_DIR" ] || python3 -m venv "$VENV_DIR"
VENV_PY="${VENV_DIR}/bin/python"
[ -x "$VENV_PY" ] || die "virtual environment at ${VENV_DIR} is broken; remove it and retry"

# Editable: the checkout stays the single source of truth, so a git pull
# is the upgrade. A wheel install would leave two copies behind.
#
# The dev extras (pytest, ruff, mypy) are opt-in. A working install should not
# drag in a test framework, and the project has no runtime dependencies at all
# - this is the one place that can add any, so it is a deliberate flag.
if [ "$WITH_DEV" -eq 1 ]; then
    say "installing StreamBridge with dev extras (editable)"
    "$VENV_PY" -m pip install --quiet --upgrade pip
    "$VENV_PY" -m pip install --quiet -e '.[dev]'
else
    say "installing StreamBridge (editable, runtime only)"
    "$VENV_PY" -m pip install --quiet --upgrade pip
    "$VENV_PY" -m pip install --quiet -e .
fi

# ------------------------------------------------------------------
#  Executables
#
#  Two console scripts from pyproject: streambridge (the CLI) and
#  streambridge-server (the daemon). Wrapper scripts rather than a bare
#  symlink, because a venv that is later moved must not break the
#  installed command.
# ------------------------------------------------------------------
mkdir -p "$BIN_DIR"
for name in streambridge streambridge-server; do
    target="${BIN_DIR}/${name}"
    cat > "$target" <<EOF
#!/bin/sh
# Generated by scripts/install.sh. Regenerate by re-running the installer.
exec "$(cd "$(dirname "$VENV_PY")" && pwd)/${name}" "\$@"
EOF
    chmod 0755 "$target"
    say "installed ${target}"
done

# ------------------------------------------------------------------
#  Configuration
# ------------------------------------------------------------------
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/streambridge"
CONF_FILE="${CONF_DIR}/config.toml"
if [ -f "$CONF_FILE" ]; then
    say "keeping existing ${CONF_FILE}"
else
    mkdir -p "$CONF_DIR"
    cp config/streambridge.example.toml "$CONF_FILE"
    say "wrote ${CONF_FILE} (every value is a working default)"
fi

# ------------------------------------------------------------------
#  Runtime directories
#
#  The unit sandboxes $HOME read-only and whitelists these two by path, so
#  they have to exist before the service starts. Creating them here is also
#  what keeps StateDirectory= out of the unit: on systemd 255 that makes a
#  user unit symlink ~/.local/state/<name> at ~/.config/<name>, which would
#  move a user's listening history into their configuration directory.
# ------------------------------------------------------------------
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/streambridge"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/streambridge"
mkdir -p "$STATE_DIR" "$CACHE_DIR"
# 0700: the state directory is a record of what was played.
chmod 700 "$STATE_DIR" "$CACHE_DIR"
say "prepared ${STATE_DIR} and ${CACHE_DIR}"

# ------------------------------------------------------------------
#  systemd user unit
# ------------------------------------------------------------------
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
if [ "$NO_SERVICE" -eq 1 ]; then
    say "skipping the systemd unit (--no-service)"
elif ! command -v systemctl >/dev/null 2>&1; then
    warn "systemctl not found; start the server yourself"
elif [ ! -d "${UNIT_DIR}" ]; then
    warn "no systemd user instance at ${UNIT_DIR}; skipping the unit"
else
    mkdir -p "$UNIT_DIR"
    sed "s|%h/.local/bin/streambridge-server|${BIN_DIR}/streambridge-server|" \
        systemd/streambridge.service > "${UNIT_DIR}/streambridge.service"

    # The unit sandboxes the home directory read-only, so MPD's
    # playlist_directory has to be whitelisted explicitly. It is
    # machine-specific, so it cannot be baked into the unit. Detect it and
    # write a drop-in; without this every queue add fails with "Access
    # denied" and the cause is not obvious from the error.
    playlist_dir=""
    for conf in "${XDG_CONFIG_HOME:-$HOME/.config}/mpd/mpd.conf" /etc/mpd.conf; do
        [ -f "$conf" ] || continue
        playlist_dir=$(sed -n 's/^[[:space:]]*playlist_directory[[:space:]]*"\([^"]*\)".*/\1/p' \
            "$conf" | tail -1)
        [ -n "$playlist_dir" ] && break
    done
    if [ -n "$playlist_dir" ]; then
        # Expand the tilde: systemd does not, so a literal ~ would silently
        # whitelist a path that does not exist.
        case "$playlist_dir" in
            "~")     playlist_dir="$HOME" ;;
            "~/"*)   playlist_dir="$HOME/${playlist_dir#~/}" ;;
        esac
        mkdir -p "$playlist_dir" 2>/dev/null || true
        mkdir -p "${UNIT_DIR}/streambridge.service.d"
        cat > "${UNIT_DIR}/streambridge.service.d/playlist-dir.conf" <<EOF
# Generated by scripts/install.sh from your mpd.conf.
# MPD only accepts a playlist load from its own playlist_directory, and
# StreamBridge writes a temporary .m3u there to attach track metadata.
[Service]
ReadWritePaths=$playlist_dir
EOF
        say "whitelisted MPD playlist_directory ${playlist_dir} for the sandbox"
    else
        warn "could not read playlist_directory from mpd.conf; queueing may fail with 'Access denied'"
    fi
    systemctl --user daemon-reload
    say "installed ${UNIT_DIR}/streambridge.service (not started)"
    printf '\n'
    printf '  systemctl --user enable --now streambridge.service\n'
    printf '  %s/health\n\n' "http://127.0.0.1:8787"
fi

# ------------------------------------------------------------------
#  Report
# ------------------------------------------------------------------
printf '\n'
say "done. Next:"
printf '  %s doctor        # check yt-dlp, mpc and MPD\n' "$BIN_DIR/streambridge"
printf '  %s --help\n' "$BIN_DIR/streambridge"
if [ "$NO_SERVICE" -eq 0 ]; then
    printf '  systemctl --user enable --now streambridge.service\n'
fi
printf '\n'
